"""Shared constants for TradeGuard services."""

EVENT_TYPES = (
    "ORDER_OPENED",
    "ORDER_CLOSED",
    "ORDER_MODIFIED",
    "POSITION_UPDATED",
    "ACCOUNT_UPDATE",
    "HEARTBEAT",
)

DECISIONS = ("ALLOW", "WARNING", "BLOCK", "EMERGENCY_STOP")
OVERTRADING_STATES = ("NORMAL", "ELEVATED", "HIGH", "CRITICAL")
ROLES = ("SUPER_ADMIN", "ADMIN", "RISK_MANAGER", "TRADER", "VIEWER")
